config/routes.rb
TweetsRails::Application.routes.draw do
  get "tweets/tweets"
  get "tweets/favorites"
  get "tweets/mentions"

  match "/tweets", :to => "tweets#tweets", :constraints => { :subdomain => /.+/ }

  match 'syncs/:type/new' => 'syncs#new', :as => :syncs_new
  match 'syncs/:type/callback' => 'syncs#callback', :as => :syncs_callback
  match 'syncs/:type/test' => 'syncs#test'
  get "syncs/setup"

  root :to => "tweets#tweets"

end

app/controllers/syncs_controller.rb
require 'yaml'

class SyncsController < ApplicationController
  def setup
  end

  def new
    # request_key and request_secret will be loaded from config/oauth/qq.yml
    client = ChinaTweet.new(params[:type], @subdomain).client
    # oauth_token is generated based on request_key and request_secret
    # cache request_token.token and request_token.secret for callback
    Rails.cache.write(build_oauth_token_key(client.name, client.oauth_token), client.dump)
    redirect_to client.authorize_url
  end

  def callback
    # load saved request_token token and secret
    data = Rails.cache.read(build_oauth_token_key(params[:type], params[:oauth_token]))
    if ChinaTweet.new(params[:type], @subdomain).process_callback(data[:request_token], data[:request_token_secret], params[:oauth_verifier])
      # oauth is successful
      render :text => 'CALLBACK OK!'
    else
      # ouath failed
      render :text => 'CALLBACK FAILED!'
    end
  end
  
  def test
    client = ChinaTweet.new(params[:type], @subdomain).client
    client.add_status('Test post')
    
    render :text => 'OK!'
  end

  private

  def build_oauth_token_key(client_name, oauth_token)
    [client_name, oauth_token].join('_')
  end

end

app/helpers/syncs_helper.rb
module SyncsHelper
end

app/views/syncs/callback.html.erb
<h1>Syncs#callback</h1>
<p>Find me in app/views/syncs/callback.html.erb</p>

app/views/syncs/new.html.erb
<h1>Syncs#new</h1>
<p>Find me in app/views/syncs/new.html.erb</p>

app/views/syncs/setup.html.erb
<% ChinaTweet.get_all_clients(@subdomain).each do |client| %>
  <p><%= client[:name] %>: <%= client[:authorized] ? 'Authorized' : link_to('Send request', syncs_new_path(:type => client[:name])) %></p>
<% end %>